output "vpc_id" { value = module.network.vpc_id }
output "public_subnet_ids" { value = module.network.public_subnet_ids }
output "app_subnet_ids" { value = module.network.app_subnet_ids }
output "db_subnet_ids" { value = module.network.db_subnet_ids }
output "alb_dns_name" { value = module.app.alb_dns_name }
output "alb_http_listener_arn" { value = module.app.alb_http_listener_arn }
output "alb_https_listener_arn" { value = module.app.alb_https_listener_arn }
output "app_base_url" { value = module.app.app_base_url }
output "cloudfront_distribution_id" { value = module.app.cloudfront_distribution_id }
output "cloudfront_distribution_domain_name" { value = module.app.cloudfront_distribution_domain_name }
output "cloudfront_aliases" { value = module.app.cloudfront_aliases }
output "cloudfront_origin_domain_name" { value = module.app.cloudfront_origin_domain_name }
output "cloudfront_standard_logs_bucket" { value = module.app.cloudfront_standard_logs_bucket }
output "cloudfront_connection_logs_enabled" { value = module.app.cloudfront_connection_logs_enabled }
output "cloudfront_viewer_mtls_enabled" { value = module.app.cloudfront_viewer_mtls_enabled }
output "cloudfront_viewer_mtls_ca_bundle_bucket" { value = module.app.cloudfront_viewer_mtls_ca_bundle_bucket }
output "cloudfront_viewer_mtls_trust_store_name" { value = module.app.cloudfront_viewer_mtls_trust_store_name }
output "s3_gateway_endpoint_id" { value = module.network.s3_gateway_endpoint_id }
output "cognito_user_pool_id" { value = module.auth.cognito_user_pool_id }
output "cognito_web_client_id" { value = module.auth.cognito_web_client_id }
output "cognito_hosted_ui_domain" { value = module.auth.cognito_hosted_ui_domain }
output "cognito_hosted_ui_base_url" { value = module.auth.cognito_hosted_ui_base_url }
output "rds_endpoint" { value = module.data.rds_endpoint }
output "rds_master_secret_arn" {
  value     = module.data.rds_master_secret_arn
  sensitive = true
}
output "central_logs_bucket" { value = module.logging.central_logs_bucket }
output "alerts_topic_arn" { value = module.automation.alerts_topic_arn }
output "global_security_alerts_topic_arn" { value = module.automation.global_security_alerts_topic_arn }
output "operations_admin_role_arn" { value = module.iam.operations_admin_role_arn }
output "security_admin_role_arn" { value = module.iam.security_admin_role_arn }
output "auditor_role_arn" { value = module.iam.auditor_role_arn }
